parameters:

- name: BuildORT
  displayName: Build ORT
  type: boolean
  default: true

- name: PostToDashboard
  displayName: Post to Dashboard
  type: boolean
  default: true

- name: RunTrtContainer
  displayName: Run in TRT Container (or set trtContainer Variable)
  type: boolean
  default: true

- name: RunMachine
  displayName: Run on Machine
  type: boolean
  default: false

<<<<<<< HEAD
=======
- name: RunPython38
  displayName: Run on Python 3.8
  type: boolean
  default: false

>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
- name: TrtVersion
  displayName: TensorRT Version
  type: string
  default: 8.0.1.6
  values:
  - 8.0.1.6
  - 7.2.3.4
  - 7.1.3.4

- name: ConfigureEPs
  displayName: Configure EPs (set epList variable - separate by spaces)
  type: boolean
  default: false

- name: PublishWheel
  displayName: Publish Wheel 
  type: boolean
  default: true

- name: ModelGroups
  type: object
  default: 
    - "onnx-zoo-models"
    - "partner-models"

- name: MemTest
  displayName: Run Memory Test
  type: boolean
  default: false

jobs: 
- job: Linux_CI_GPU_TENSORRT_PERF
  pool:
    name: Linux-GPU-TensorRT-Perf 
    demands:
    - Agent.Name -equals K8S-HVZD1T2CL-HVZD1T2

  variables:
<<<<<<< HEAD
    - name: trt_dockerfile
      ${{ if eq(parameters.TrtVersion, '8.0.1.6') }}:
        value: Dockerfile.ubuntu_cuda11_3_tensorrt8_0
      ${{ if eq(parameters.TrtVersion, '7.2.3.4') }}:
        value: Dockerfile.ubuntu_cuda11_1_tensorrt7_2
      ${{ if eq(parameters.TrtVersion, '7.1.3.4') }}:
        value: Dockerfile.ubuntu_cuda10_2_tensorrt7_1
    - name: build_args
      ${{ if eq(parameters.RunTrtContainer, true) }}:
        value: Dockerfile.tensorrt-perf -t $(trtContainer) -o $(Build.SourcesDirectory)/dockerfiles/Dockerfile.tensorrt
      ${{ if ne(parameters.RunTrtContainer, true) }}:
        value: Dockerfile.custom-trt-perf -t ${{ parameters.TrtVersion }} -o $(Build.SourcesDirectory)/tools/ci_build/github/linux/docker/$(trt_dockerfile)
=======
    - name: build
      ${{ if eq(parameters.RunTrtContainer, true) }}:
        value: Dockerfile.tensorrt-perf -t $(trtContainer) -o $(Build.SourcesDirectory)/dockerfiles/Dockerfile.tensorrt
>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
    - name: environment
      ${{ if ne(parameters.RunMachine, true) }}:
        value: docker.sh -d ort-$(branch) -p $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf 
      ${{ if eq(parameters.RunMachine, true) }}:
<<<<<<< HEAD
        value: machine.sh
    - name: with_arguments
      value: $(environment) -e "$(epList)"
=======
        value: machine.sh 
    - name: with_arguments
      value: $(environment) -e "$(epList)" 
   
>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
  timeoutInMinutes: 3000 
      
  steps:
    
    - ${{ if eq(parameters.MemTest, true) }}:
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/run_mem_test_docker.sh -d ort-$(branch) -p $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/'
        displayName: 'Run Memory Test'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/'

    - ${{ if eq(parameters.BuildORT, true) }}:

      - ${{ if ne(parameters.RunMachine, true) }}:
<<<<<<< HEAD
        - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/build_image.sh -p $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/$(build_args) -b $(branch) -i ort-$(branch)'
=======
        - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/build_image.sh -p $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/$(build) -b $(branch) -i ort-$(branch)'
>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
          displayName: 'Build latest ORT Images'
          workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build'
          
      - ${{ if eq(parameters.RunMachine, true) }}:
        - script: 'python3 $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/ort_build_latest.py -b $(branch) -c /usr/local/cuda -o ~/repos/onnxruntime/ -t ${{ parameters.TrtVersion }}'
          displayName: 'Build latest ORT'
          workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build'
<<<<<<< HEAD
        
    - ${{ if and(eq(parameters.PublishWheel, true), eq(variables.trtContainer, '21.07')) }}:
    
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/copy_wheel.sh -t $(trtContainer)'
        displayName: 'Copy Wheel from Docker'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build'
    
      - script: 'OUTPUT=$(ls dist) && az storage blob upload --account-name anubiscustomerstorage  --account-key $(account-key) --container-name upload --file $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/dist/*.whl --name ort-trt-ep/$OUTPUT'
        displayName: 'Upload Wheel File'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'

      - task: PowerShell@2
        inputs:
          filePath: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/start_job.ps1'
          arguments: '-file_folder $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/dist -account_key $(account-key) -trt_container $(trtContainer)'
        displayName: 'Start Anubis Job'
      
    - ${{ if eq(parameters.MemTest, true) }}:
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/run_mem_test_docker.sh -d ort-$(branch) -p $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/ -w /code/ -l false'
        displayName: 'Run Memory Test'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/'

    - ${{ each option in parameters.ModelGroups }}:
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/run_perf_$(with_arguments) -o ${{option}} -m $(${{option}})'
        displayName: '${{option}} perf'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'
=======
    
    - ${{ if eq(parameters.RunPython38, true) }}:
        - script: 'docker build --build-arg IMAGE=ort-$(branch) -t ort-$(branch) -f $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build/Dockerfile.python38 .'
          displayName: 'Build latest ORT Images'
          workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/build'
          
    - ${{ if eq(parameters.PublishWheel, true) }}:
    
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/anubis/copy_wheel.sh -t $(trtContainer)'
        displayName: 'Copy Wheel from Docker'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/anubis'
    
      - script: 'OUTPUT=$(ls dist) && az storage blob upload --account-name anubiscustomerstorage  --account-key $(account-key) --container-name upload --file $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/dist/*.whl --name ort-trt-ep/$OUTPUT'
        displayName: 'Upload Wheel File'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'

      - task: PowerShell@2
        inputs:
          filePath: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/anubis/start_job.ps1'
          arguments: '-file_folder $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/dist -account_key $(account-key) -trt_container $(trtContainer)'
        displayName: 'Start Anubis Job'

    - ${{ each option in parameters.ModelGroups }}:
      - script: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/run_perf_$(with_arguments) -o ${{option}} -m $(${{option}})'
        displayName: '${{option}} perf'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'
>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
  
    - script: 'mkdir $(Build.SourcesDirectory)/Artifact'
      displayName: 'Prepare Artifacts Directory'
      workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'
      condition: always() 

    - ${{ if not(eq(length(parameters.ModelGroups), 0)) }}:
      - script: 'cp -r $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/result/ $(Build.SourcesDirectory)/Artifact'
        displayName: 'Copy Artifacts'
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'
    
    - ${{ if eq(parameters.MemTest, true) }}:
      - script: 'cp -r $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/mem_test/build/result $(Build.SourcesDirectory)/Artifact/result_mem_test'
        displayName: 'Copy Artifacts'
<<<<<<< HEAD
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'
        condition: always()

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Artifact'
        artifactName: 'result-$(Build.BuildNumber)'

    - ${{ if eq(parameters.PostToDashboard, true) }}:
      - script: 'python $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/post.py -r $(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/result -c $(Build.SourceVersion) -u "https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=$(Build.BuildId)" -t ${{ parameters.TrtVersion }} -b $(branch)' 
        displayName: 'Post to Dashboard'
=======
>>>>>>> 6ecf626a9c491caffe3bd481d638b27d14534a6f
        workingDirectory: '$(Build.SourcesDirectory)/onnxruntime/python/tools/tensorrt/perf/'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.SourcesDirectory)/Artifact'
        artifactName: 'result-$(Build.BuildNumber)'

    - script: sudo rm -rf $(Agent.BuildDirectory)
      displayName: Clean build files (POSIX)
      condition: not(eq(variables['Agent.OS'], 'Windows_NT')) # and always()
      continueOnError: true  # continuing on error for this step, since linux build folder is somehow getting permission issue
      
- job: Linux_CI_GPU_TENSORRT_PERF_DASHBOARD
  dependsOn: Linux_CI_GPU_TENSORRT_PERF
  pool:
    name: Linux-GPU-TensorRT-Perf 
    demands:
    - Agent.Name -equals cus-cpu-52wc
  
  steps: 
  - ${{ if eq(parameters.PostToDashboard, true) }}:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'result-$(Build.BuildNumber)'

    - script: conda activate clean && python $(Build.SourcesDirectory)\onnxruntime\python\tools\tensorrt\perf\post.py -r $(Pipeline.Workspace)\result -c $(Build.SourceVersion) -u "https://dev.azure.com/onnxruntime/onnxruntime/_build/results?buildId=$(Build.BuildId)" -t ${{ parameters.TrtVersion }} -b $(branch)
      displayName: 'Post to Dashboard'
      env:
        DASHBOARD_MYSQL_ORT_PASSWORD: $(dashboard-mysql-ort-password)

  - script: rd /S /Q $(Agent.BuildDirectory)
    displayName: Clean build files (Windows)
    condition: eq(variables['Agent.OS'], 'Windows_NT') # and always()